export const Besluit = () => {
  return (
     <article>
    <h2>Besluit</h2>
    <p>
      Uit het werk kunnen we besluiten dat de hiërarchie van de Romeinen goed in elkaar zat aangezien iedereen zijn plaats kende en er respect en aanzien was. Door deze organisatie was het Romeinse leger een van de succesvolste legers uit die tijd. Wanneer we het huidige leger vergelijken met het Romeinse stellen we vast dat onze hiërarchie een zeer uitgebreide versie is van die van het Romeinse leger. Er zijn meer onderverdelingen en meer componenten dan bij de Romeinen, maar dit is te wijten aan technologische en wetenschappelijke vooruitgang. Zo zijn er nu vliegtuigen, tanks, jeeps en vliegdekschepen wat ervoor zorgt dat iedere persoon binnen het leger zijn specifieke functie heeft en er dus meer verdeeldheid is.
      Op het vlak van bewapening waren de Romeinen ook goed voorzien. Ze waren veel bezig met het ontwikkelen van nieuwe wapens om hun vijanden te kunnen verrassen. Hun wapens waren efficiënt en doeltreffend waardoor ze vele veldslagen hebben gewonnen. Wanneer we het Romeinse leger met het huidige vergelijken stellen we vast dat alles is veranderd. Dit is weer te wijten aan technologische en wetenschappelijke vooruitgang. In huidige tijden wordt er niet meer gestreden met zwaarden, schilden en speren, maar met machinegeweren, langeafstandsraketten en computers. De Romeinen waren ongetwijfeld de grondleggers van verscheidene legers die later zijn ontstaan, maar sporen van hun wapens zijn in het huidige leger niet meer te vinden.
      Het Romeinse leger was een van de succesvolste legers uit de geschiedenis. Dit is te wijten aan hun ijzersterke discipline en goed bedachte tactieken en aanvalsplannen. De Romeinen begrepen ook zeer goed dat een veldslag niet enkel fysiek werd gestreden, maar ook mentaal. Ze wisten goed hoe ze het moreel bij hun troepen hoog moesten houden terwijl ze dat van de vijand verzwakten. Het verlies van een veldslag vond zijn oorzaak meestal bij slecht leiderschap. De tactieken van het huidige leger zijn zeer sterk veranderd aangezien alles vanop een langere afstand gebeurt en er meer en meer via robots wordt gewerkt. Vroeger waren bijna alle gevechten man tot man gevechten waardoor men tactieken kon toepassen zoals bijvoorbeeld: ruiters langs de flanken laten inkomen. Tegenwoordig heeft dit geen nut meer aangezien het aantal soldaten waarmee men oorlog voert sterk verminderd is.
    </p>
  </article>
  );
};
